### PR TITLE
Added sponsor logo and link to code challenge

### PR DESCRIPTION
**Pull request by rkunboxed**
Invertase is sponsoring the code challenge so I added their logo and a link to their site to the code challenge.

Screenshot 2023-11-04 at 2 08 39 PM

Screenshot 2023-11-05 at 6 37 16 AM

### CODE REVIEW

**Comment by Farahkh** [comment]
the view is broken in mobile
image

**Review by Farahkh — CHANGES_REQUESTED** [review]
the view is broken in mobile
image

**Review by Farahkh — APPROVED** [review]
approved

**Review by Stef-GMS — APPROVED** [review]
Approved

**Pull request merged**
