### PR TITLE
Added code challenge content with links. Cleaned up linter warnings.

### PR DESCRIPTION
**Pull request by rkunboxed**
Screenshot 2023-10-31 at 6 43 43 AM

mobile

### CODE REVIEW

**Review by Stef-GMS — CHANGES_REQUESTED** [review]
@rkunboxed It looks like your changes undid what @Farahkh pushed before your update.  Please take a look.

**Review by Farahkh — APPROVED** [review]
Approved

**Comment by Farahkh** [comment]
@Stef-GMS I think we should be able to implement only the file Rona created/changed? and that is the code challenge file and the conference page and that way my work will not be affected.

**Review by Farahkh — APPROVED** [review]
Perfect

**Review by Stef-GMS — APPROVED** [review]
Approved

**Review by Stef-GMS — APPROVED** [review]
Approved

**Review by Farahkh — APPROVED** [review]
approved

**Pull request merged**
